### ISSUE TITLE
在linux上的火狐浏览器访问会显示ws链接找不到

### ISSUE THREAD

**Issue by ghost** [OddCN/screen-share-to-browser#9]

**Comment by ghost** [comment]
0.0.0.0:8012 [screen.html:46:25
     http://10.45.51.32:8123/screen.html)
WebSocket is supported by your Browser! screen.html:60:21
Firefox can’t establish a connection to the server at ws://0.0.0.0:8012/. screen.html:62:17
Connection is closed...

**Comment by aswallz** [comment]
![Uploading Screenshot_20220503-132224_屏幕分享.png…]()

**Comment by ghost** [comment]
![Screenshot](https://user-images.githubusercontent.com/102346830/166407804-7dee5aeb-28d3-4776-9da1-e27e38a7d80e.png)

ws获取不到局域网地址导致无法投屏

**Comment by ghost** [comment]
建议增加ip修改的功能
